"""added new field 'measurement_method to Challenge'

Revision ID: 0313ac066b9f
Revises: cbd79ef8cfc4
Create Date: 2025-03-03 20:24:27.800026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0313ac066b9f'
down_revision: Union[str, None] = 'cbd79ef8cfc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('challenges', sa.Column('measurement_method', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('challenges', 'measurement_method')
    # ### end Alembic commands ###
