"""Added new fields to Exercise and WorkoutExercise

Revision ID: 112225d56191
Revises: 6ed4de5b4387
Create Date: 2025-02-13 12:29:38.645329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '112225d56191'
down_revision: Union[str, None] = '6ed4de5b4387'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
