"""Modded Exercise-Workout relationship

Revision ID: 667f4a5ee259
Revises: c7136fe9ffe1
Create Date: 2025-02-05 09:28:54.321686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '667f4a5ee259'
down_revision: Union[str, None] = 'c7136fe9ffe1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
