"""Added new field image_url to Exercise

Revision ID: 912938745c1c
Revises: 8057b4f9e18e
Create Date: 2025-02-17 20:20:59.261735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '912938745c1c'
down_revision: Union[str, None] = '8057b4f9e18e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('image_url', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercises', 'image_url')
    # ### end Alembic commands ###
