"""Added new fields to Exercise and WorkoutExercise

Revision ID: 93da09819f0e
Revises: f5224c03990b
Create Date: 2025-02-13 12:12:47.675247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '93da09819f0e'
down_revision: Union[str, None] = 'f5224c03990b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workout_exercise', 'exercise_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('workout_exercise', 'reps',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_workout_exercise_id'), 'workout_exercise', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workout_exercise_id'), table_name='workout_exercise')
    op.alter_column('workout_exercise', 'reps',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('workout_exercise', 'exercise_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
