"""Add measurement_method enum

Revision ID: ba794c664889
Revises: 7bb6f8f3518d
Create Date: 2025-04-06 10:36:45.694421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ba794c664889'
down_revision: Union[str, None] = '7bb6f8f3518d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('challenges', 'measurement_method',
               existing_type=mysql.ENUM('DOWN_UP', 'PROXIMITY', 'STILLNESS'),
               type_=sa.Enum('downUpMovement', 'proximity', 'stillness', name='measurementmethodenum'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('challenges', 'measurement_method',
               existing_type=sa.Enum('downUpMovement', 'proximity', 'stillness', name='measurementmethodenum'),
               type_=mysql.ENUM('DOWN_UP', 'PROXIMITY', 'STILLNESS'),
               existing_nullable=False)
    # ### end Alembic commands ###
