"""Named countReps to count_reps

Revision ID: cbd79ef8cfc4
Revises: 75252b9d69d6
Create Date: 2025-03-02 10:34:15.472423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cbd79ef8cfc4'
down_revision: Union[str, None] = '75252b9d69d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('challenges', sa.Column('count_reps', sa.Boolean(), nullable=False))
    op.drop_column('challenges', 'countReps')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('challenges', sa.Column('countReps', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.drop_column('challenges', 'count_reps')
    # ### end Alembic commands ###
