"""deleted count_reps field

Revision ID: ef5dda3ca02f
Revises: ac43120688ea
Create Date: 2025-04-28 21:49:55.938631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ef5dda3ca02f'
down_revision: Union[str, None] = 'ac43120688ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('challenges', 'duration',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_column('challenges', 'count_reps')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('challenges', sa.Column('count_reps', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.alter_column('challenges', 'duration',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
