"""Added new fields to Exercise and WorkoutExercise

Revision ID: f5224c03990b
Revises: be9602a58dd8
Create Date: 2025-02-13 11:55:18.878920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f5224c03990b'
down_revision: Union[str, None] = 'be9602a58dd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('duration_based', sa.Boolean(), nullable=True))
    op.add_column('workout_exercise', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('workout_exercise', sa.Column('sets', sa.Integer(), nullable=True))
    op.add_column('workout_exercise', sa.Column('duration', sa.Integer(), nullable=True))
    op.add_column('workout_exercise', sa.Column('rest_time', sa.Integer(), nullable=True))
    op.alter_column('workout_exercise', 'exercise_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('workout_exercise', 'reps',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_workout_exercise_id'), 'workout_exercise', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workout_exercise_id'), table_name='workout_exercise')
    op.alter_column('workout_exercise', 'reps',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('workout_exercise', 'exercise_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_column('workout_exercise', 'rest_time')
    op.drop_column('workout_exercise', 'duration')
    op.drop_column('workout_exercise', 'sets')
    op.drop_column('workout_exercise', 'id')
    op.drop_column('exercises', 'duration_based')
    # ### end Alembic commands ###
